import './globals.css'

import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const geist = Geist({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary',
})

type RootLayoutProps = {
	children: React.ReactNode
	params: Promise<{ locale: string }>
}

export default async function RootLayout(props: Readonly<RootLayoutProps>) {
	const { children } = props
	const locale = await getLocale()
	const messages = await getMessages()
	return (
		<ClerkProvider>
			<html lang={locale}>
				<body className={`${geist.variable} antialiased`}>
					<NextIntlClientProvider messages={messages}>
						{children}
					</NextIntlClientProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
