import './globals.css'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const geist = Geist({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR">
			<body className={`${geist.variable} antialiased`}>{children}</body>
		</html>
	)
}
