import './globals.css'

import { getLocale, getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import { ptBR, enUS } from '@clerk/localizations'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist } from 'next/font/google'
import type { Metadata } from 'next'

import { Toaster } from '@/components/ui/toaster'
import { LOCALES } from '@/constants/general'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const geist = Geist({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary',
})

type RootLayoutProps = {
	children: React.ReactNode
	params: Promise<{ locale: string }>
}

export default async function RootLayout(props: Readonly<RootLayoutProps>) {
	const { children } = props
	const locale = await getLocale()
	const messages = await getMessages()
	const clerkLocalization = locale === LOCALES.en ? enUS : ptBR
	return (
		<ClerkProvider localization={clerkLocalization}>
			<html lang={locale}>
				<body className={`${geist.variable} antialiased`}>
					<NextIntlClientProvider messages={messages}>
						{children}
					</NextIntlClientProvider>
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	)
}
