import '../globals.css'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const geist = Geist({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary',
})

type RootLayoutProps = {
	children: React.ReactNode
	params: Promise<{ locale: string }>
}

export default async function RootLayout(props: Readonly<RootLayoutProps>) {
	const { children, params } = props
	const locale = (await params).locale
	return (
		<html lang={locale}>
			<body className={`${geist.variable} antialiased`}>{children}</body>
		</html>
	)
}
